project_name: plataforma-ia-industrial
databases:
  - name: duckdb-plataforma
    templates:
      - columns
      - preview
    profiling:
      refresh_policy: "interval"
      interval_days: 1
    include: []
    exclude: []
    type: duckdb
    path: ./plataforma.duckdb
repos: []
notion: null
llm: null
slack: null
